# bot settings
bot_token: 'YOUR_BOT_TOKEN' # support bot token
staffchat_id: 'SUPERGROUP_CHAT_ID' # eg. -123456789
owner_id: 'YOUR_TELEGRAM_ID'
spam_time: 300000 # time (in MS) in which user may send 5 messages
spam_cant_msg: 5

parse_mode: 'Markdown' # Experimental. Do not change unless you know what you are doing. Options: Markdown/MarkdownV2/HTML

allow_private: false # Allow / disallow option for staff to chat privately
direct_reply: false # Set this to true to just forward staff users to a user chat when allow_private
auto_close_tickets: false # Close tickets after answering
anonymous_tickets: true # Include userid in tickets or not
anonymous_replies: true # Include staff member name in response
show_auto_replied: false # Send auto replied msgs to staff chat
show_user_ticket: false # Show ticket id to user
autoreply_confirmation: true # Reply with language.confirmationMessage on each incoming message
clean_replies: false # Remove footer and header from response
pass_start: false # Pass /start command to support directly

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server

dev_mode: false # Enable/disable dev mode

# customize your language
language:
  startCommandText: 'Selamat datang dalam Group IT Support GKInvest. Sampaikan pesan anda atau masukan _command_ /help untuk bantuan bot.'
  faqCommandText: 'Kunjungi : [github.com](https://github.com/nisamrf/telegram-support-bot.git) untuk mendapatkan info dan commit terbaru bot.'
  helpCommandText: "*Available commands:* \n /faquser - menampilkan _frequently asked question_ \n /id - menampilkan id percakapan."
  helpCommandStaffText: "*Command tersedia:*\n
    /start - Berikan sedikit perkenalan bot \n
    /faq - Tunjukan faq (frequently asked questions) \n
    /open - *Staff* Tunjukan ticket yang masih berjalan \n
    /reopen - *Staff* Reopen ticket yang telah diselesaikan \n
    /close - *Staff* Reply pada chat ticket untuk menyelesaikan ticket dan melakukan unban \n
    /clear - *Staff* Tutup semua ticket yang masih berjalan \n
    /ban - *Staff* Ban user dari chat \n
    /unban - *Staff* Unban user"
  confirmationMessage: "Terimakasih sudah mengubungi kami, kami akan jawab pesan anda secepat mungkin. "
  blockedSpam: 'Mohon maaf kamu mengirimkan terlalu banyak chat. Mohon bersabar sampai staff kami mereview ticket anda.'
  ticket: 'Ticket'
  closed: 'closed'
  acceptedBy: 'was accepted by'
  dear: 'Hi'
  regards: 'Regards,'
  from: 'from'
  language: 'Language'
  msg_sent: 'Pesan dikirimkan ke user'
  file_sent: 'File dikirimkan ke user'
  usr_with_ticket: 'User dengan ticket'
  banned: 'banned'
  replyPrivate: 'Dijawab dalam private chat'
  services: 'Select a service from the list below'
  customer: 'customer'
  msgForwarding: 'Pesan anda akan diteruskan ke group Support: ''
  back: 'Kembali'
  whatSubCategory: 'Which subcategory describes your needs the best? '
  prvChatEnded: 'Private chat ended.'
  prvChatOpened: 'Private Chat opened with customer.'
  prvChatEnd: 'End Private chat'
  prvChatOpenedCustomer: 'Opened private chat'
  instructionsSent: 'Instructions were sent to you in private chat.'
  openTickets: 'Open Tickets'
  support: 'Support'
  prvChatOnly: 'Command ini hanya dapat digunakan dalam private chat.'
  ticketClosed: 'Ticket anda diselesaikan oleh staff kami, silahkan hubungi kami kembali di lain waktu dengan memasukan command /start atau masukan command /help untuk bantuan bot.'
  links: 'Direct support links'
  textFirst: 'Mohon untuk mengirimkan pesan dahulu agar kami dapat mereview ticket anda lebih baik.'
  ticketClosedError: 'Anda tidak dapat membalas ticket yang sudah di close.'
  automatedReply: 'Ini adalah pesan otomatis.'
  automatedReplyAuthor: 'IT Support GKInvest'
  doesntHelp: 'This does not help.'
  automatedReplySent: 'Pesan otomatis dikirimkan ke user.'
  ticketReopened: 'Ticket dibuka kembali.'
  regardsGroup: 'IT Support GKInvest'

autoreply:
#  - question: 'install'
#    answer: "If you want to install the bot, you can use the following link: \
#      [Getting Started](https://github.com/bostrot/telegram-support-bot/wiki/Getting-started)  \
#      Alternatively you can also use our one-click setup & hosting service: \
#      [Botspace](https://botspace.bostrot.com/)"
#  - question: 'are you sure?'
#    answer: 'Yes.'
# categories:
#  - name: "Category1"
#    subgroups:
#    - name: "Sub1"
#      group_id: "-12345678910"
#    - name: "Sub2"
#      group_id: "-12345678910"
#    - name: "Sub3"
#      group_id: "-12345678910"
#  - name: "Category2"
#    subgroups:
#    - name: "Sub4"
#      group_id: "-12345678910"
#    - name: "Sub5"
#      group_id: "-12345678910"
#    - name: "Sub6"
#      group_id: "-12345678910"
#  - name: "Category with no subcategories"
#    group_id: "-12345678910"
#  - name: "Admin Chat"
#    group_id: "-12345678910"
#  - name: "Other issues"
#    tag: "#other"
#    msg: "Please specify your order number and describe the problem in as much detail as possible"
#    group_id: "-12345678910"
#  - name: "Contact"
#    msg: "Check out our Website"
